version: '3'
services:
  propostas:
    image: gdevides/proposta
    ports:
      - 8080:8080
    environment:
      DB_HOST: propostasdb
      DB_NAME: proposta
      DB_PORT: 3366
      DB_USERNAME: root
      DB_PASSWORD: root
      FEING_NOVA_PROPOSTA: analise:9999/api/solicitacao
      FEING_CONSULTA_CARTAO: http://contas:8888/api/cartoes
      INTERVALO_CONSULTA_CARTAO: 100000
      KEYCLOAK_ISSUER_URI: http://keycloak:18080/auth/realms/nosso-cartao
      KEYCLOAK_JWKS_URI: http://keycloak:18080/auth/realms/nosso-cartao/protocol/openid-connect/certs
      JAEGER_ENABLED: "true"
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      JAEGER_SAMPLER: 1
      ENCRYPTOR_SENHA: 123456
      ENCRYPTOR_SALT: 654321
    depends_on:
      - propostasdb

  propostasdb:
    image: mysql:5.7
    ports:
      - 3366:3366
    environment:
      MYSQL_DATABASE: proposta
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_TCP_PORT: 3366
    volumes:
        - propostasdb-volume:/var/lib/mysql

volumes:
  propostasdb-volume:
